# Generated by Django 4.1.1 on 2022-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_comment_options_alter_comment_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
