# Generated by Django 4.1.1 on 2022-09-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_comment_options_alter_comment_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
