# Generated by Django 4.1.1 on 2022-10-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_comment_text_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
