# Generated by Django 4.1.1 on 2022-10-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_user_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
