# Generated by Django 4.1.1 on 2022-10-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_author_post_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
