# Generated by Django 4.1.1 on 2022-10-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_comment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
    ]
