# Generated by Django 4.1.1 on 2022-10-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_remove_category_subscribers_delete_usercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
